version: '3.3'

volumes:
  db-data:
    external: false

services:
  db:
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: caio
      POSTGRES_PASSWORD: caio
      DB_PORT: 5432
      DB_DATABASE: blog_development
    image: postgres:12.2
    volumes:
      - db-data:/usr/local/pgsql/data

  app:
    env_file: ./config/sample.env
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
      - "5432:5432"
    depends_on:
      - db
