version: '3.3'

services:
  db:
    container_name: postgres
    environment:
      POSTGRES_DB: blog_development
      POSTGRES_USER: caio
      POSTGRES_PASSWORD: caio
      DB_PORT: 5432
      DB_DATABASE: articles
    image: postgres:10.12

  app:
    command: /enjublog/entrypoint.sh
    container_name: app
    env_file: ./config/sample.env
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    

